import {
  Essentials,
  Bold,
  Italic,
  Heading,
  Paragraph,
  Indent,
  Link,
  List,
  MediaEmbed,
  Highlight,
  Table,
  Font,
  Alignment,
  Strikethrough,
  RemoveFormat,
  FindAndReplace,
  Image,
  ImageUpload,
  Underline,
  ImageToolbar,
  ImageCaption,
  ImageStyle,
} from "ckeditor5";

export const ckEditorConfigs = {
  licenseKey: "GPL",
  plugins: [
    Essentials,
    Bold,
    Italic,
    Heading,
    Underline,
    Paragraph,
    Indent,
    Link,
    List,
    MediaEmbed,
    ImageUpload,
    FindAndReplace,
    Table,
    Font,
    Alignment,
    Strikethrough,
    RemoveFormat,
    Highlight,
    Image,
    ImageUpload,
    ImageToolbar,
    ImageCaption,
    ImageStyle,
  ],
  toolbar: {
   items: [
     "undo",
    "redo",
    "|",
    "heading",
    "|",
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "removeFormat",
    "|",
    "link",
    "|",
    "alignment",
    "|",
    "bulletedList",
    "numberedList",
    "outdent",
    "indent",
    "|",
    "insertTable",
    "mediaEmbed",
    "|",
    "fontSize",
    "fontColor",
    "fontBackgroundColor",
    "|",
    "highlight",
    "|",
    "findAndReplace",
    "selectAll",
    "|", "uploadImage", "imageStyle:side",
   ],
    shouldNotGroupWhenFull: true,
  },
   image: {
    toolbar: [
      "imageTextAlternative",
      "toggleImageCaption",
      "imageStyle:inline",
      "imageStyle:block",
      "imageStyle:side",
    ],
  },
};
